// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT5xxnoMhejhqfTi25RJvhXwA0LSZbU80',
    appId: '1:471855761398:web:ae0395ae7a754e85b429d7',
    messagingSenderId: '471855761398',
    projectId: 'fir-practice1-db8a0',
    authDomain: 'fir-practice1-db8a0.firebaseapp.com',
    databaseURL: 'https://fir-practice1-db8a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice1-db8a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPdcPdSrtU_oXEM3ZurZpLJ1Aac3WRlM0',
    appId: '1:471855761398:android:b7b82794937e84a0b429d7',
    messagingSenderId: '471855761398',
    projectId: 'fir-practice1-db8a0',
    databaseURL: 'https://fir-practice1-db8a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice1-db8a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsiK-2EyTLB6xHHiiatdryW576alC3x0s',
    appId: '1:471855761398:ios:2bacbf14222a6fcdb429d7',
    messagingSenderId: '471855761398',
    projectId: 'fir-practice1-db8a0',
    databaseURL: 'https://fir-practice1-db8a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice1-db8a0.appspot.com',
    iosClientId: '471855761398-5ob633vpo9k56001o6k78t2989sumt2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudSiswaFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsiK-2EyTLB6xHHiiatdryW576alC3x0s',
    appId: '1:471855761398:ios:2bacbf14222a6fcdb429d7',
    messagingSenderId: '471855761398',
    projectId: 'fir-practice1-db8a0',
    databaseURL: 'https://fir-practice1-db8a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice1-db8a0.appspot.com',
    iosClientId: '471855761398-5ob633vpo9k56001o6k78t2989sumt2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudSiswaFirebase',
  );
}
